stages:
  - build
  - test
  - publish

image: maven:3.9.6-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

# ========================
# 1️⃣ BUILD JOB
# ========================
build:
  stage: build
  script:
    - java -version
    - mvn -version
    - mvn -B clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

# ========================
# 2️⃣ TEST JOB (Matrix Browsers)
# ========================
test:
  stage: test
  parallel:
    matrix:
      - BROWSER: "chrome-headless"
      - BROWSER: "firefox-headless"
  script:
    - mvn -B test -q -Dbrowser=$BROWSER -DthreadCount=4 -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - ExtentReport/
    reports:
      junit: target/surefire-reports/TEST-*.xml
    expire_in: 1 week

# ========================
# 3️⃣ PUBLISH JOB
# ========================
publish:
  stage: publish
  needs: ["build"]
  script:
    - mkdir staging
    - cp target/*.jar staging || true
  artifacts:
    paths:
      - staging/
    expire_in: 1 week