#################################################################################
####						COMMON TEST DATA								####
#################################################################################

#Selenium specific parameters
WebDriverWaitDuration=3
PageFactoryWaitDuration=30
ScreenshotLocation=ExtentReport/screenshots
#################################################################################
####						ENVIRONMENT SPECIFIC TEST DATA					####
################################################################################
LOGIN_PAGE_URL = https://automationexercise.com/login
API_URL=https://automationexercise.com/api
